export interface RundownTemplateEvent {
  session: string;
  start_time: string;
  end_time: string | null;
  title: string;
  description: string | null;
  pic: string | null;
  location: string | null;
}

export interface RundownTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  events: RundownTemplateEvent[];
}

export const RUNDOWN_TEMPLATES: RundownTemplate[] = [
  {
    id: "akad-nikah",
    name: "Akad Nikah",
    description: "Rundown khusus prosesi akad nikah / ijab kabul",
    icon: "mosque",
    events: [
      {
        session: "Akad Nikah",
        start_time: "07:00",
        end_time: "07:30",
        title: "Persiapan & Dekorasi Akad",
        description: "Tim dekorasi mempersiapkan pelaminan dan meja akad",
        pic: "Tim Dekorasi",
        location: "Ruang Akad",
      },
      {
        session: "Akad Nikah",
        start_time: "07:30",
        end_time: "08:00",
        title: "Penyambutan Tamu Undangan",
        description: "Tamu undangan keluarga mulai berdatangan",
        pic: "Penerima Tamu",
        location: "Pintu Masuk",
      },
      {
        session: "Akad Nikah",
        start_time: "08:00",
        end_time: "08:15",
        title: "Prosesi Masuk Pengantin Wanita",
        description: "Pengantin wanita memasuki ruangan diiringi keluarga",
        pic: "MC",
        location: "Ruang Akad",
      },
      {
        session: "Akad Nikah",
        start_time: "08:15",
        end_time: "08:30",
        title: "Pembacaan Ayat Suci Al-Quran",
        description: "Tilawah Al-Quran sebelum prosesi akad dimulai",
        pic: "Qori",
        location: "Ruang Akad",
      },
      {
        session: "Akad Nikah",
        start_time: "08:30",
        end_time: "08:45",
        title: "Sambutan Wali Nikah",
        description: "Sambutan dari pihak keluarga mempelai wanita",
        pic: "Wali Nikah",
        location: "Ruang Akad",
      },
      {
        session: "Akad Nikah",
        start_time: "08:45",
        end_time: "09:00",
        title: "Prosesi Ijab Kabul",
        description: "Prosesi akad nikah dipimpin oleh penghulu KUA",
        pic: "Penghulu",
        location: "Ruang Akad",
      },
      {
        session: "Akad Nikah",
        start_time: "09:00",
        end_time: "09:15",
        title: "Penandatanganan Buku Nikah",
        description: "Penandatanganan dokumen pernikahan resmi",
        pic: "Penghulu",
        location: "Meja Akad",
      },
      {
        session: "Akad Nikah",
        start_time: "09:15",
        end_time: "09:30",
        title: "Penyerahan Mahar",
        description: "Prosesi penyerahan mahar dari pengantin pria ke wanita",
        pic: "Pengantin Pria",
        location: "Ruang Akad",
      },
      {
        session: "Akad Nikah",
        start_time: "09:30",
        end_time: "10:00",
        title: "Doa & Sungkeman",
        description: "Doa pernikahan dan prosesi sungkeman kepada orang tua",
        pic: "Pemimpin Doa",
        location: "Ruang Akad",
      },
      {
        session: "Akad Nikah",
        start_time: "10:00",
        end_time: "11:00",
        title: "Sesi Foto Keluarga",
        description: "Foto bersama keluarga inti kedua mempelai",
        pic: "Fotografer",
        location: "Area Foto",
      },
      {
        session: "Akad Nikah",
        start_time: "11:00",
        end_time: "12:00",
        title: "Makan Siang & Ramah Tamah",
        description: "Santap siang bersama keluarga dan tamu undangan",
        pic: "Catering",
        location: "Ruang Makan",
      },
    ],
  },
  {
    id: "resepsi-siang",
    name: "Resepsi Siang",
    description: "Rundown resepsi pernikahan sesi siang (11.00 - 15.00)",
    icon: "sun",
    events: [
      {
        session: "Resepsi",
        start_time: "09:00",
        end_time: "10:30",
        title: "Persiapan Venue & Sound Check",
        description: "Pengecekan sound system, catering, dan dekorasi",
        pic: "Wedding Organizer",
        location: "Gedung Resepsi",
      },
      {
        session: "Resepsi",
        start_time: "10:30",
        end_time: "11:00",
        title: "Briefing Tim & Pengantin",
        description: "Briefing akhir dengan seluruh tim dan kedua pengantin",
        pic: "Wedding Organizer",
        location: "Ruang Persiapan",
      },
      {
        session: "Resepsi",
        start_time: "11:00",
        end_time: "11:30",
        title: "Pembukaan & Penyambutan Tamu",
        description: "Tamu mulai hadir, disambut oleh keluarga",
        pic: "Penerima Tamu",
        location: "Pintu Masuk",
      },
      {
        session: "Resepsi",
        start_time: "11:30",
        end_time: "12:00",
        title: "Prosesi Masuk Pengantin",
        description: "Pengantin memasuki gedung diiringi musik dan alunan lagu",
        pic: "MC",
        location: "Panggung Utama",
      },
      {
        session: "Resepsi",
        start_time: "12:00",
        end_time: "12:15",
        title: "Pembacaan Ayat Suci Al-Quran",
        description: "Tilawah pembuka resepsi",
        pic: "Qori",
        location: "Panggung",
      },
      {
        session: "Resepsi",
        start_time: "12:15",
        end_time: "12:30",
        title: "Sambutan Keluarga",
        description: "Sambutan dari orang tua kedua mempelai",
        pic: "MC",
        location: "Panggung",
      },
      {
        session: "Resepsi",
        start_time: "12:30",
        end_time: "13:00",
        title: "Makan Siang",
        description: "Tamu undangan menikmati hidangan",
        pic: "Catering",
        location: "Area Makan",
      },
      {
        session: "Resepsi",
        start_time: "13:00",
        end_time: "14:00",
        title: "Hiburan & Sesi Foto Tamu",
        description: "Penampilan musik/hiburan & tamu berfoto dengan pengantin",
        pic: "MC & Fotografer",
        location: "Panggung & Pelaminan",
      },
      {
        session: "Resepsi",
        start_time: "14:00",
        end_time: "14:30",
        title: "Potong Kue & Sesi Momen Spesial",
        description: "Prosesi potong kue pengantin dan suap-suapan",
        pic: "MC",
        location: "Pelaminan",
      },
      {
        session: "Resepsi",
        start_time: "14:30",
        end_time: "15:00",
        title: "Penutupan & Foto Keluarga",
        description: "Sesi foto keluarga besar dan penutupan acara",
        pic: "MC & Fotografer",
        location: "Pelaminan",
      },
    ],
  },
  {
    id: "resepsi-malam",
    name: "Resepsi Malam",
    description: "Rundown resepsi pernikahan sesi malam (18.00 - 22.00)",
    icon: "moon",
    events: [
      {
        session: "Resepsi Malam",
        start_time: "16:00",
        end_time: "17:30",
        title: "Persiapan & Gladi Resik",
        description: "Gladi resik prosesi masuk dan pengecekan teknis",
        pic: "Wedding Organizer",
        location: "Gedung Resepsi",
      },
      {
        session: "Resepsi Malam",
        start_time: "17:30",
        end_time: "18:00",
        title: "Pengantin Siap Berbusana",
        description: "Make-up dan busana final pengantin",
        pic: "Make Up Artist",
        location: "Ruang Rias",
      },
      {
        session: "Resepsi Malam",
        start_time: "18:00",
        end_time: "18:30",
        title: "Penyambutan Tamu",
        description: "Tamu undangan mulai hadir disambut oleh keluarga",
        pic: "Penerima Tamu",
        location: "Pintu Masuk",
      },
      {
        session: "Resepsi Malam",
        start_time: "18:30",
        end_time: "19:00",
        title: "Pembukaan Acara",
        description: "Pembukaan oleh MC dan penampilan pembuka",
        pic: "MC",
        location: "Panggung Utama",
      },
      {
        session: "Resepsi Malam",
        start_time: "19:00",
        end_time: "19:30",
        title: "Prosesi Masuk Pengantin",
        description: "Grand entrance pengantin diiringi lagu spesial",
        pic: "MC",
        location: "Lorong Masuk",
      },
      {
        session: "Resepsi Malam",
        start_time: "19:30",
        end_time: "19:45",
        title: "Sambutan & Doa",
        description: "Sambutan keluarga dan doa keberkahan",
        pic: "MC",
        location: "Panggung",
      },
      {
        session: "Resepsi Malam",
        start_time: "19:45",
        end_time: "20:30",
        title: "Makan Malam & Hiburan",
        description: "Makan malam dan penampilan live music",
        pic: "Catering & Band",
        location: "Area Makan",
      },
      {
        session: "Resepsi Malam",
        start_time: "20:30",
        end_time: "21:00",
        title: "Sesi Foto Tamu dengan Pengantin",
        description: "Antrian tamu berfoto bersama pengantin di pelaminan",
        pic: "Fotografer",
        location: "Pelaminan",
      },
      {
        session: "Resepsi Malam",
        start_time: "21:00",
        end_time: "21:30",
        title: "Potong Kue & First Dance",
        description: "Prosesi potong kue dan tarian pertama pengantin",
        pic: "MC",
        location: "Dance Floor",
      },
      {
        session: "Resepsi Malam",
        start_time: "21:30",
        end_time: "22:00",
        title: "Penutupan & Foto Bersama",
        description: "Penutupan resmi, foto keluarga, dan ucapan terima kasih",
        pic: "MC",
        location: "Pelaminan",
      },
    ],
  },
  {
    id: "pernikahan-adat-jawa",
    name: "Adat Jawa",
    description: "Rundown pernikahan adat Jawa lengkap dengan prosesi tradisional",
    icon: "scroll",
    events: [
      {
        session: "Siraman",
        start_time: "07:00",
        end_time: "08:00",
        title: "Prosesi Siraman",
        description: "Ritual siraman oleh orang tua dan sesepuh keluarga",
        pic: "Sesepuh Adat",
        location: "Rumah Pengantin",
      },
      {
        session: "Siraman",
        start_time: "08:00",
        end_time: "09:00",
        title: "Midodareni",
        description: "Malam midodareni - pengantin wanita didoakan oleh ibu-ibu",
        pic: "Sesepuh Adat",
        location: "Ruang Keluarga",
      },
      {
        session: "Akad Nikah",
        start_time: "09:00",
        end_time: "10:30",
        title: "Prosesi Ijab Kabul",
        description: "Akad nikah resmi dipimpin penghulu",
        pic: "Penghulu",
        location: "Ruang Akad",
      },
      {
        session: "Resepsi",
        start_time: "10:30",
        end_time: "11:00",
        title: "Prosesi Panggih",
        description: "Prosesi temu manten - pengantin pria dan wanita dipertemukan",
        pic: "Sesepuh Adat",
        location: "Pelaminan",
      },
      {
        session: "Resepsi",
        start_time: "11:00",
        end_time: "11:20",
        title: "Balangan Suruh",
        description: "Melempar daun sirih sebagai simbol sudah saling mengenal",
        pic: "Sesepuh Adat",
        location: "Pelaminan",
      },
      {
        session: "Resepsi",
        start_time: "11:20",
        end_time: "11:40",
        title: "Wiji Dadi",
        description: "Pengantin pria menginjak telur sebagai simbol tanggung jawab",
        pic: "Sesepuh Adat",
        location: "Pelaminan",
      },
      {
        session: "Resepsi",
        start_time: "11:40",
        end_time: "12:00",
        title: "Sindur Binayang",
        description: "Orang tua mengiringi pengantin ke pelaminan dengan kain sindur",
        pic: "Orang Tua",
        location: "Pelaminan",
      },
      {
        session: "Resepsi",
        start_time: "12:00",
        end_time: "12:30",
        title: "Dhahar Klimah",
        description: "Pengantin saling menyuapi nasi kuning",
        pic: "Sesepuh Adat",
        location: "Pelaminan",
      },
      {
        session: "Resepsi",
        start_time: "12:30",
        end_time: "13:30",
        title: "Sungkeman & Foto Keluarga",
        description: "Sungkeman kepada orang tua dan foto bersama keluarga",
        pic: "Fotografer",
        location: "Pelaminan",
      },
      {
        session: "Resepsi",
        start_time: "13:30",
        end_time: "15:00",
        title: "Makan Siang & Penerimaan Tamu",
        description: "Tamu undangan hadir dan menikmati hidangan",
        pic: "MC",
        location: "Gedung",
      },
    ],
  },
  {
    id: "hari-penuh",
    name: "Sehari Penuh (Akad + Resepsi)",
    description: "Rundown lengkap dari pagi akad hingga malam resepsi",
    icon: "calendar",
    events: [
      {
        session: "Persiapan",
        start_time: "05:30",
        end_time: "07:00",
        title: "Make Up & Rias Pengantin",
        description: "Proses rias dan busana pengantin wanita",
        pic: "Make Up Artist",
        location: "Ruang Rias",
      },
      {
        session: "Akad Nikah",
        start_time: "07:00",
        end_time: "07:30",
        title: "Penyambutan Tamu Akad",
        description: "Keluarga inti dan saksi mulai berdatangan",
        pic: "Penerima Tamu",
        location: "Ruang Akad",
      },
      {
        session: "Akad Nikah",
        start_time: "07:30",
        end_time: "07:45",
        title: "Prosesi Masuk Mempelai",
        description: "Kedua mempelai memasuki ruangan akad",
        pic: "MC",
        location: "Ruang Akad",
      },
      {
        session: "Akad Nikah",
        start_time: "07:45",
        end_time: "08:00",
        title: "Pembacaan Al-Quran & Khutbah Nikah",
        description: "Tilawah dan khutbah sebelum prosesi akad",
        pic: "Qori & Penghulu",
        location: "Ruang Akad",
      },
      {
        session: "Akad Nikah",
        start_time: "08:00",
        end_time: "08:30",
        title: "Ijab Kabul",
        description: "Prosesi akad nikah resmi",
        pic: "Penghulu",
        location: "Meja Akad",
      },
      {
        session: "Akad Nikah",
        start_time: "08:30",
        end_time: "09:00",
        title: "Penyerahan Mahar & Sungkeman",
        description: "Penyerahan mahar dan sungkeman kepada orang tua",
        pic: "Sesepuh",
        location: "Ruang Akad",
      },
      {
        session: "Akad Nikah",
        start_time: "09:00",
        end_time: "10:00",
        title: "Foto Akad & Keluarga",
        description: "Sesi foto keluarga inti pasca akad",
        pic: "Fotografer",
        location: "Area Foto",
      },
      {
        session: "Istirahat",
        start_time: "10:00",
        end_time: "11:00",
        title: "Makan Siang & Istirahat",
        description: "Santap bersama keluarga dan persiapan resepsi",
        pic: "Catering",
        location: "Ruang Makan",
      },
      {
        session: "Persiapan Resepsi",
        start_time: "11:00",
        end_time: "12:00",
        title: "Ganti Busana Resepsi",
        description: "Pengantin berganti busana untuk resepsi",
        pic: "Make Up Artist",
        location: "Ruang Rias",
      },
      {
        session: "Resepsi",
        start_time: "12:00",
        end_time: "12:30",
        title: "Pembukaan Resepsi",
        description: "MC membuka acara resepsi",
        pic: "MC",
        location: "Gedung Resepsi",
      },
      {
        session: "Resepsi",
        start_time: "12:30",
        end_time: "13:00",
        title: "Prosesi Masuk Pengantin",
        description: "Grand entrance pengantin ke gedung resepsi",
        pic: "MC",
        location: "Lorong Masuk",
      },
      {
        session: "Resepsi",
        start_time: "13:00",
        end_time: "13:15",
        title: "Sambutan Keluarga",
        description: "Sambutan dari orang tua kedua pihak",
        pic: "MC",
        location: "Panggung",
      },
      {
        session: "Resepsi",
        start_time: "13:15",
        end_time: "14:30",
        title: "Makan Siang & Penerimaan Tamu",
        description: "Tamu undangan hadir dan berfoto dengan pengantin",
        pic: "MC & Fotografer",
        location: "Gedung Resepsi",
      },
      {
        session: "Resepsi",
        start_time: "14:30",
        end_time: "15:00",
        title: "Potong Kue & Penutupan",
        description: "Prosesi potong kue dan penutupan resmi acara",
        pic: "MC",
        location: "Pelaminan",
      },
    ],
  },
];
